# GENERATED BY PHASE B RESUME: 2025-11-02T07:27:06Z
"""
Test suite for Permission Management System.

Tests PermissionManager class functionality including:
- Permission checking with wildcard support
- Admin detection
- Role-based access control
- Database fallback mechanisms
"""

import pytest
from unittest.mock import Mock, MagicMock

from core.permissions import PermissionManager, permission_manager, check_permission
from models import User, Role, Permission


class TestPermissionManager:
    """Test PermissionManager class."""
    
    def test_init(self):
        """Test PermissionManager initialization."""
        pm = PermissionManager()
        assert pm is not None
        assert isinstance(pm._permission_cache, dict)
        assert isinstance(pm._fallback_permissions, dict)
    
    def test_superuser_has_all_permissions(self):
        """Test that superusers have access to everything."""
        pm = PermissionManager()
        
        # Create mock superuser
        user = Mock(spec=User)
        user.username = "superuser"
        user.is_superuser = True
        user.roles = []
        
        # Superuser should have any permission
        assert pm.has_permission(user, "admin.full_access") is True
        assert pm.has_permission(user, "users.view") is True
        assert pm.has_permission(user, "nonexistent.permission") is True
    
    def test_admin_wildcard_access(self):
        """Test admin users get wildcard access."""
        pm = PermissionManager()
        
        # Create mock admin user
        admin_role = Mock(spec=Role)
        admin_role.code = "admin"
        admin_role.name = "Administrator"
        
        user = Mock(spec=User)
        user.username = "admin"
        user.is_superuser = False
        user.roles = [admin_role]
        
        # Admin should have wildcard access
        assert pm.is_admin(user) is True
        assert pm.has_permission(user, "users.view") is True
        assert pm.has_permission(user, "accounting.edit") is True
    
    def test_has_permission_direct_match(self):
        """Test direct permission matching."""
        pm = PermissionManager()
        
        # Create mock user with specific permission
        role = Mock(spec=Role)
        role.code = "accountant"
        role.name = "Accountant"
        
        user = Mock(spec=User)
        user.username = "testuser"
        user.is_superuser = False
        user.roles = [role]
        
        # Should have permissions from fallback for accountant role
        assert pm.has_permission(user, "accounting.view") is True
        assert pm.has_permission(user, "reports.view") is True
        # Should not have admin permissions
        assert pm.has_permission(user, "users.delete") is False
    
    def test_has_permission_module_wildcard(self):
        """Test module-level wildcard permissions."""
        pm = PermissionManager()
        
        # Mock a user with module wildcard
        role = Mock(spec=Role)
        role.code = "inventory_manager"
        
        user = Mock(spec=User)
        user.username = "inv_user"
        user.is_superuser = False
        user.roles = [role]
        
        # Should have inventory permissions from fallback
        assert pm.has_permission(user, "inventory.view") is True
        assert pm.has_permission(user, "inventory.create") is True
        assert pm.has_permission(user, "inventory.edit") is True
    
    def test_is_admin_with_admin_role(self):
        """Test is_admin with admin role."""
        pm = PermissionManager()
        
        admin_role = Mock(spec=Role)
        admin_role.code = "admin"
        
        user = Mock(spec=User)
        user.username = "admin1"
        user.is_superuser = False
        user.roles = [admin_role]
        
        assert pm.is_admin(user) is True
    
    def test_is_admin_with_administrator_role(self):
        """Test is_admin with administrator role variant."""
        pm = PermissionManager()
        
        admin_role = Mock(spec=Role)
        admin_role.code = "administrator"
        
        user = Mock(spec=User)
        user.username = "admin2"
        user.is_superuser = False
        user.roles = [admin_role]
        
        assert pm.is_admin(user) is True
    
    def test_is_admin_with_non_admin_role(self):
        """Test is_admin returns False for non-admin users."""
        pm = PermissionManager()
        
        role = Mock(spec=Role)
        role.code = "cashier"
        
        user = Mock(spec=User)
        user.username = "cashier1"
        user.is_superuser = False
        user.roles = [role]
        
        assert pm.is_admin(user) is False
    
    def test_permissions_for_role_fallback(self):
        """Test getting permissions for a role from fallback."""
        pm = PermissionManager()
        
        permissions = pm.permissions_for_role("admin")
        assert "admin.full_access" in permissions
        assert "users.view" in permissions
        assert "users.create" in permissions
        
        permissions = pm.permissions_for_role("cashier")
        assert "sales.view" in permissions
        assert "sales.create" in permissions
        assert "inventory.view" in permissions
        # Should not have admin permissions
        assert "users.delete" not in permissions
    
    def test_permissions_for_unknown_role(self):
        """Test getting permissions for unknown role returns empty set."""
        pm = PermissionManager()
        
        permissions = pm.permissions_for_role("nonexistent_role")
        assert isinstance(permissions, set)
        assert len(permissions) == 0
    
    def test_get_user_modules(self):
        """Test getting list of modules user has access to."""
        pm = PermissionManager()
        
        role = Mock(spec=Role)
        role.code = "accountant"
        
        user = Mock(spec=User)
        user.username = "acc1"
        user.is_superuser = False
        user.roles = [role]
        
        modules = pm.get_user_modules(user)
        assert isinstance(modules, list)
        assert "accounting" in modules
        assert "reports" in modules
    
    def test_validate_permission_code_valid(self):
        """Test validating valid permission codes."""
        pm = PermissionManager()
        
        assert pm.validate_permission_code("users.view") is True
        assert pm.validate_permission_code("accounting.edit") is True
        assert pm.validate_permission_code("admin.full_access") is True
        assert pm.validate_permission_code("module.*") is True
    
    def test_validate_permission_code_invalid(self):
        """Test validating invalid permission codes."""
        pm = PermissionManager()
        
        assert pm.validate_permission_code("") is False
        assert pm.validate_permission_code("no_dot") is False
        assert pm.validate_permission_code("too.many.dots") is False
        assert pm.validate_permission_code("users.invalid_action") is False
        assert pm.validate_permission_code(None) is False
    
    def test_clear_cache(self):
        """Test cache clearing."""
        pm = PermissionManager()
        
        # Populate cache
        pm._permission_cache["test"] = {"perm1", "perm2"}
        pm._role_cache["test"] = "admin"
        pm._cache_valid = True
        
        # Clear cache
        pm.clear_cache()
        
        assert len(pm._permission_cache) == 0
        assert len(pm._role_cache) == 0
        assert pm._cache_valid is False
    
    def test_check_permission_convenience_function(self):
        """Test the check_permission convenience function."""
        role = Mock(spec=Role)
        role.code = "admin"
        
        user = Mock(spec=User)
        user.username = "admin"
        user.is_superuser = False
        user.roles = [role]
        
        # Should work through global permission_manager
        assert check_permission(user, "users.view") is True
    
    def test_permission_denied_for_missing_permission(self):
        """Test that users without permission are denied."""
        pm = PermissionManager()
        
        role = Mock(spec=Role)
        role.code = "cashier"
        
        user = Mock(spec=User)
        user.username = "cashier1"
        user.is_superuser = False
        user.roles = [role]
        
        # Cashier should not have admin permissions
        assert pm.has_permission(user, "users.delete") is False
        assert pm.has_permission(user, "accounting.edit") is False
    
    def test_error_handling_in_has_permission(self):
        """Test that errors are handled gracefully in has_permission."""
        pm = PermissionManager()
        
        # Create user that will raise exception when accessing roles
        user = Mock(spec=User)
        user.username = "bad_user"
        user.is_superuser = False
        user.roles = Mock(side_effect=Exception("Database error"))
        
        # Should return False on error (fail securely)
        assert pm.has_permission(user, "users.view") is False
    
    def test_multiple_roles_combined_permissions(self):
        """Test that user with multiple roles gets combined permissions."""
        pm = PermissionManager()
        
        role1 = Mock(spec=Role)
        role1.code = "cashier"
        
        role2 = Mock(spec=Role)
        role2.code = "inventory_manager"
        
        user = Mock(spec=User)
        user.username = "multi_role"
        user.is_superuser = False
        user.roles = [role1, role2]
        
        # Should have permissions from both roles
        assert pm.has_permission(user, "sales.view") is True  # from cashier
        assert pm.has_permission(user, "inventory.edit") is True  # from inventory_manager


class TestGlobalPermissionManager:
    """Test the global permission_manager instance."""
    
    def test_global_instance_exists(self):
        """Test that global permission_manager exists."""
        assert permission_manager is not None
        assert isinstance(permission_manager, PermissionManager)
    
    def test_global_instance_is_singleton(self):
        """Test that we use a single global instance."""
        from core.permissions import permission_manager as pm1
        from core.permissions import permission_manager as pm2
        assert pm1 is pm2
