# GENERATED BY PHASE B RESUME: 2025-11-02T07:27:06Z
"""
Test suite for UI Module Contract.

Verifies all UI modules implement the ModuleUI contract properly.
"""

import pytest
import importlib
from unittest.mock import Mock

from ui.base_ui import ModuleUI, ModuleWidget, ModuleMainWindow


# List of all UI modules that should implement ModuleUI
UI_MODULES = [
    ("ui.users_window", "UsersWindow"),
    ("ui.roles_window", "RolesWindow"),
    ("ui.company_window", "CompanyWindow"),
    ("ui.branches_window", "BranchesWindow"),
    ("ui.products_window", "ProductsWindow"),
    ("ui.categories_window", "CategoriesWindow"),
    ("ui.stock_movements_window", "StockMovementsWindow"),
    ("ui.accounts_window", "AccountsWindow"),
    ("ui.journals_window", "JournalsWindow"),
    ("ui.trial_balance_window", "TrialBalanceWindow"),
    ("ui.inventory_valuation_window", "InventoryValuationWindow"),
    ("ui.pos_interface_window", "POSInterfaceWindow"),
    ("ui.sales_history_window", "SalesHistoryWindow"),
    ("ui.customers_window", "CustomersWindow"),
    ("ui.suppliers_window", "SuppliersWindow"),
    ("ui.purchase_orders_window", "PurchaseOrdersWindow"),
    ("ui.goods_receipt_window", "GoodsReceiptWindow"),
    ("ui.purchase_invoices_window", "PurchaseInvoicesWindow"),
    ("ui.reports_window", "ReportsWindow"),
    ("ui.settings_window", "SettingsWindow"),
]


class TestModuleUIContract:
    """Test UI module contract implementation."""
    
    @pytest.mark.parametrize("module_path,class_name", UI_MODULES)
    def test_module_imports(self, module_path, class_name):
        """Test that all UI modules can be imported."""
        module = importlib.import_module(module_path)
        assert hasattr(module, class_name), f"{class_name} not found in {module_path}"
    
    @pytest.mark.parametrize("module_path,class_name", UI_MODULES)
    def test_module_inherits_from_moduleui(self, module_path, class_name):
        """Test that UI modules inherit from ModuleUI."""
        module = importlib.import_module(module_path)
        cls = getattr(module, class_name)
        assert issubclass(cls, ModuleUI), f"{class_name} does not inherit from ModuleUI"
    
    @pytest.mark.parametrize("module_path,class_name", UI_MODULES)
    def test_module_has_load_data_method(self, module_path, class_name):
        """Test that UI modules implement load_data method."""
        module = importlib.import_module(module_path)
        cls = getattr(module, class_name)
        assert hasattr(cls, "load_data"), f"{class_name} does not implement load_data()"
        assert callable(getattr(cls, "load_data")), f"{class_name}.load_data is not callable"
    
    def test_moduleui_is_abstract(self):
        """Test that ModuleUI cannot be instantiated directly."""
        with pytest.raises(TypeError):
            ModuleUI()
    
    def test_modulewidget_can_be_instantiated(self):
        """Test that ModuleWidget can be used as base class."""
        # ModuleWidget itself has abstract method, so we can't instantiate it
        # but we can check it's properly defined
        assert issubclass(ModuleWidget, ModuleUI)
        assert hasattr(ModuleWidget, "load_data")
    
    def test_modulemainwindow_can_be_used_as_base(self):
        """Test that ModuleMainWindow can be used as base class."""
        assert issubclass(ModuleMainWindow, ModuleUI)
        assert hasattr(ModuleMainWindow, "load_data")
    
    @pytest.mark.parametrize("module_path,class_name", UI_MODULES[:5])  # Test subset
    def test_module_has_required_signals(self, module_path, class_name):
        """Test that UI modules have required signals."""
        module = importlib.import_module(module_path)
        cls = getattr(module, class_name)
        
        # Check that class definition includes ModuleUI signals
        # (inherited, so they should be available)
        assert hasattr(ModuleUI, "data_loaded")
        assert hasattr(ModuleUI, "data_loading")
        assert hasattr(ModuleUI, "error_occurred")
    
    def test_moduleui_provides_required_methods(self):
        """Test that ModuleUI base class provides all required methods."""
        required_methods = [
            "load_data",
            "refresh_view",
            "get_session_context",
            "has_permission",
            "is_admin",
            "_show_error",
            "_show_info",
            "_show_warning",
            "_ask_confirmation",
        ]
        
        for method_name in required_methods:
            assert hasattr(ModuleUI, method_name), f"ModuleUI missing method: {method_name}"
    
    def test_moduleui_provides_properties(self):
        """Test that ModuleUI provides required properties."""
        required_properties = ["is_loading", "is_data_loaded", "last_error"]
        
        for prop_name in required_properties:
            assert hasattr(ModuleUI, prop_name), f"ModuleUI missing property: {prop_name}"


class TestModuleUIFunctionality:
    """Test ModuleUI functionality with mock implementation."""
    
    def test_refresh_view_calls_load_data(self, qtbot):
        """Test that refresh_view calls load_data."""
        # Skip if PyQt6 not available in test environment
        pytest.importorskip("PyQt6")
        
        from PyQt6.QtWidgets import QWidget
        
        class TestModule(ModuleWidget):
            def __init__(self):
                self.load_data_called = False
                super().__init__()
            
            def load_data(self, session):
                self.load_data_called = True
        
        # Create instance with mock context
        mock_session_factory = Mock()
        mock_session = Mock()
        mock_session.__enter__ = Mock(return_value=mock_session)
        mock_session.__exit__ = Mock(return_value=False)
        mock_session_factory.return_value = mock_session
        
        module = TestModule()
        module.session_factory = mock_session_factory
        
        # Call refresh_view
        module.refresh_view()
        
        # Verify load_data was called
        assert module.load_data_called is True
    
    def test_has_permission_uses_permission_manager(self):
        """Test that has_permission calls permission_manager."""
        from ui.base_ui import ModuleUI
        from unittest.mock import MagicMock
        
        # Create a concrete implementation for testing
        class TestModule(ModuleUI):
            def load_data(self, session):
                pass
        
        # Mock user and permission manager
        mock_user = Mock()
        mock_pm = Mock()
        mock_pm.has_permission = Mock(return_value=True)
        
        module = TestModule.__new__(TestModule)
        module.current_user = mock_user
        module.permission_manager = mock_pm
        
        # Test permission check
        result = module.has_permission("users.view")
        
        assert result is True
        mock_pm.has_permission.assert_called_once_with(mock_user, "users.view")
