# GENERATED BY PHASE B RESUME: 2025-11-02T07:27:06Z
"""
Database Utilities for Hassad ERP.

Provides helper functions and context managers for safe database operations
with automatic session management, transaction handling, and error recovery.
"""

import logging
from contextlib import contextmanager
from typing import Generator, Optional

from sqlalchemy.orm import Session
from sqlalchemy.exc import SQLAlchemyError

from core.database import SessionLocal

# Configure logging
logger = logging.getLogger(__name__)


@contextmanager
def session_scope() -> Generator[Session, None, None]:
    """
    Provide a transactional scope for database operations.
    
    This context manager automatically handles:
    - Session creation
    - Transaction commit on success
    - Rollback on error
    - Session cleanup
    
    Usage:
        with session_scope() as session:
            user = session.query(User).first()
            user.name = "Updated Name"
            # Commit happens automatically on exit
            
    Yields:
        Session: Active database session
        
    Raises:
        SQLAlchemyError: If database operation fails
    """
    session = SessionLocal()
    try:
        yield session
        session.commit()
        logger.debug("Database transaction committed successfully")
    except SQLAlchemyError as e:
        session.rollback()
        logger.error(f"Database transaction rolled back due to error: {e}")
        raise
    except Exception as e:
        session.rollback()
        logger.error(f"Unexpected error in database transaction: {e}")
        raise
    finally:
        session.close()
        logger.debug("Database session closed")


@contextmanager
def read_only_session() -> Generator[Session, None, None]:
    """
    Provide a read-only session for query operations.
    
    This context manager is optimized for read-only operations:
    - No automatic commit
    - Automatic rollback to ensure clean state
    - Faster than session_scope for queries
    
    Usage:
        with read_only_session() as session:
            users = session.query(User).all()
            
    Yields:
        Session: Active database session for reads
    """
    session = SessionLocal()
    try:
        yield session
    except Exception as e:
        logger.error(f"Error in read-only session: {e}")
        raise
    finally:
        session.rollback()  # Clean up any pending operations
        session.close()
        logger.debug("Read-only session closed")


def safe_execute(session: Session, operation, *args, **kwargs):
    """
    Execute a database operation with error handling.
    
    Args:
        session: Active database session
        operation: Callable database operation
        *args: Positional arguments for operation
        **kwargs: Keyword arguments for operation
        
    Returns:
        Result of operation or None if failed
        
    Example:
        result = safe_execute(session, session.query(User).filter_by, username="admin")
    """
    try:
        result = operation(*args, **kwargs)
        return result
    except SQLAlchemyError as e:
        logger.error(f"Database operation failed: {e}")
        session.rollback()
        return None
    except Exception as e:
        logger.error(f"Unexpected error in database operation: {e}")
        session.rollback()
        return None


def refresh_entity(session: Session, entity) -> bool:
    """
    Refresh an entity from database.
    
    Args:
        session: Active database session
        entity: Entity to refresh
        
    Returns:
        bool: True if refresh successful, False otherwise
    """
    try:
        session.refresh(entity)
        logger.debug(f"Refreshed entity: {entity}")
        return True
    except SQLAlchemyError as e:
        logger.error(f"Failed to refresh entity: {e}")
        return False


def expunge_entity(session: Session, entity) -> bool:
    """
    Remove entity from session without deleting from database.
    
    Args:
        session: Active database session
        entity: Entity to expunge
        
    Returns:
        bool: True if expunge successful, False otherwise
    """
    try:
        session.expunge(entity)
        logger.debug(f"Expunged entity: {entity}")
        return True
    except Exception as e:
        logger.error(f"Failed to expunge entity: {e}")
        return False


class DBTransaction:
    """
    Database transaction manager for complex operations.
    
    Provides more control over transactions with savepoints,
    nested transactions, and manual commit/rollback.
    
    Usage:
        tx = DBTransaction()
        try:
            session = tx.begin()
            # ... operations ...
            tx.commit()
        except Exception:
            tx.rollback()
        finally:
            tx.close()
    """
    
    def __init__(self):
        self.session: Optional[Session] = None
        self._active = False
    
    def begin(self) -> Session:
        """Start new transaction and return session."""
        if self._active:
            raise RuntimeError("Transaction already active")
        
        self.session = SessionLocal()
        self._active = True
        logger.debug("Transaction started")
        return self.session
    
    def commit(self) -> bool:
        """Commit current transaction."""
        if not self._active or not self.session:
            logger.warning("No active transaction to commit")
            return False
        
        try:
            self.session.commit()
            logger.debug("Transaction committed")
            return True
        except SQLAlchemyError as e:
            logger.error(f"Transaction commit failed: {e}")
            self.rollback()
            return False
    
    def rollback(self) -> bool:
        """Rollback current transaction."""
        if not self._active or not self.session:
            logger.warning("No active transaction to rollback")
            return False
        
        try:
            self.session.rollback()
            logger.debug("Transaction rolled back")
            return True
        except Exception as e:
            logger.error(f"Transaction rollback failed: {e}")
            return False
    
    def close(self):
        """Close session and end transaction."""
        if self.session:
            self.session.close()
            logger.debug("Transaction session closed")
        
        self.session = None
        self._active = False
    
    def __enter__(self):
        """Context manager entry."""
        return self.begin()
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit with automatic commit/rollback."""
        if exc_type is not None:
            self.rollback()
        else:
            self.commit()
        self.close()
