"""
Purchases & Suppliers Module
Handles Purchase Orders, Goods Receipts, Purchase Invoices, and Supplier Management
"""

from .schemas import (
    SupplierCreate,
    SupplierRead,
    SupplierUpdate,
    SupplierCatalogCreate,
    POCreate,
    POUpdate,
    PORead,
    POLineSchema,
    GRNCreate,
    GRNLineSchema,
    GRNRead,
    InvoiceCreate,
    InvoiceLineSchema,
    InvoiceRead,
    ApprovalRequestCreate,
    ApprovalActionSchema,
    PaymentCreate,
    PaymentRead,
)

from .services import (
    create_supplier,
    get_supplier,
    list_suppliers,
    create_purchase_order,
    submit_purchase_order,
    approve_purchase_order,
    reject_purchase_order,
    cancel_purchase_order,
    create_goods_receipt,
    create_purchase_invoice,
    verify_purchase_invoice,
    post_purchase_invoice,
    record_supplier_payment,
    create_approval_request,
    act_on_approval,
    get_purchase_order,
    get_goods_receipt,
    get_purchase_invoice,
)

__all__ = [
    # Schemas
    "SupplierCreate",
    "SupplierRead",
    "SupplierUpdate",
    "SupplierCatalogCreate",
    "POCreate",
    "POUpdate",
    "PORead",
    "POLineSchema",
    "GRNCreate",
    "GRNLineSchema",
    "GRNRead",
    "InvoiceCreate",
    "InvoiceLineSchema",
    "InvoiceRead",
    "ApprovalRequestCreate",
    "ApprovalActionSchema",
    "PaymentCreate",
    "PaymentRead",
    # Services
    "create_supplier",
    "get_supplier",
    "list_suppliers",
    "create_purchase_order",
    "submit_purchase_order",
    "approve_purchase_order",
    "reject_purchase_order",
    "cancel_purchase_order",
    "create_goods_receipt",
    "create_purchase_invoice",
    "verify_purchase_invoice",
    "post_purchase_invoice",
    "record_supplier_payment",
    "create_approval_request",
    "act_on_approval",
    "get_purchase_order",
    "get_goods_receipt",
    "get_purchase_invoice",
]
