"""
Customers Window.

Provides full CRUD management for customers: create, edit, delete (soft),
search and view, wired to :class:`CustomerService` in the services layer.
All business logic (validation, code generation) lives in the service; this
module only handles presentation and user interaction.
"""

import logging
import uuid
from decimal import Decimal
from typing import Any, Dict, Optional

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QCheckBox,
    QDialog,
    QDoubleSpinBox,
    QFormLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QTableWidget,
    QTableWidgetItem,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)
from sqlalchemy.orm import Session

from core.database import SessionLocal
from core.db_utils import session_scope
from core.services import get_customer_service, ValidationError
from models import Customer
from ui.base_ui import ModuleWidget

logger = logging.getLogger(__name__)


class CustomerDialog(QDialog):
    """Dialog for creating/editing a customer."""

    def __init__(
        self,
        customer: Optional[Customer] = None,
        parent: Optional[QWidget] = None,
    ) -> None:
        """
        Initialize the dialog.

        Args:
            customer: Existing customer to edit, or None to create a new one.
            parent: Parent widget.
        """
        super().__init__(parent)
        self.customer = customer
        self.is_edit = customer is not None
        self._setup_ui()
        if self.is_edit:
            self._load_customer_data()

    def _setup_ui(self) -> None:
        """Build the form UI."""
        self.setWindowTitle(
            "Edit Customer | تعديل العميل"
            if self.is_edit
            else "Create Customer | إنشاء عميل"
        )
        self.setMinimumWidth(520)

        layout = QVBoxLayout(self)
        form = QFormLayout()

        # Code (optional - auto-generated by the service when left blank).
        self.code_input = QLineEdit()
        self.code_input.setPlaceholderText("Auto-generated | يُولَّد تلقائياً")
        form.addRow("Code | الرمز", self.code_input)

        # Name (required).
        self.name_input = QLineEdit()
        form.addRow("Name (English) | الاسم (إنجليزي) *", self.name_input)

        # Arabic name.
        self.name_ar_input = QLineEdit()
        form.addRow("Name (Arabic) | الاسم (عربي)", self.name_ar_input)

        # Phone.
        self.phone_input = QLineEdit()
        self.phone_input.setPlaceholderText("Optional | اختياري")
        form.addRow("Phone | الهاتف", self.phone_input)

        # Email.
        self.email_input = QLineEdit()
        self.email_input.setPlaceholderText("Optional | اختياري")
        form.addRow("Email | البريد الإلكتروني", self.email_input)

        # Tax id.
        self.tax_id_input = QLineEdit()
        self.tax_id_input.setPlaceholderText("Optional | اختياري")
        form.addRow("Tax ID | الرقم الضريبي", self.tax_id_input)

        # Address.
        self.address_input = QTextEdit()
        self.address_input.setMaximumHeight(80)
        self.address_input.setPlaceholderText("Optional | اختياري")
        form.addRow("Address | العنوان", self.address_input)

        # Credit limit.
        self.credit_limit_input = QDoubleSpinBox()
        self.credit_limit_input.setMaximum(9_999_999_999.99)
        self.credit_limit_input.setDecimals(2)
        self.credit_limit_input.setGroupSeparatorShown(True)
        form.addRow("Credit Limit | الحد الائتماني", self.credit_limit_input)

        # Active.
        self.active_checkbox = QCheckBox("Active | نشط")
        self.active_checkbox.setChecked(True)
        form.addRow("", self.active_checkbox)

        layout.addLayout(form)

        # Action buttons.
        button_layout = QHBoxLayout()
        button_layout.addStretch()

        cancel_btn = QPushButton("Cancel | إلغاء")
        cancel_btn.clicked.connect(self.reject)
        button_layout.addWidget(cancel_btn)

        save_btn = QPushButton("Save | حفظ")
        save_btn.setProperty("primary", True)
        save_btn.setDefault(True)
        save_btn.clicked.connect(self.accept)
        button_layout.addWidget(save_btn)

        layout.addLayout(button_layout)

    def _load_customer_data(self) -> None:
        """Populate the form with the existing customer's values."""
        if not self.customer:
            return
        self.code_input.setText(self.customer.code or "")
        self.name_input.setText(self.customer.name or "")
        self.name_ar_input.setText(self.customer.name_ar or "")
        self.phone_input.setText(self.customer.phone or "")
        self.email_input.setText(self.customer.email or "")
        self.tax_id_input.setText(self.customer.tax_id or "")
        self.address_input.setPlainText(self.customer.address or "")
        if self.customer.credit_limit is not None:
            self.credit_limit_input.setValue(float(self.customer.credit_limit))
        self.active_checkbox.setChecked(bool(self.customer.is_active))

    def get_customer_data(self) -> Dict[str, Any]:
        """Collect form values into a service-ready dictionary."""
        return {
            "code": self.code_input.text().strip() or None,
            "name": self.name_input.text().strip(),
            "name_ar": self.name_ar_input.text().strip() or None,
            "phone": self.phone_input.text().strip() or None,
            "email": self.email_input.text().strip() or None,
            "tax_id": self.tax_id_input.text().strip() or None,
            "address": self.address_input.toPlainText().strip() or None,
            "credit_limit": Decimal(str(self.credit_limit_input.value())),
            "is_active": self.active_checkbox.isChecked(),
        }


class CustomersWindow(ModuleWidget):
    """Customers management window with full CRUD."""

    def __init__(
        self,
        app_context: Optional[Dict[str, Any]] = None,
        parent: Optional[QWidget] = None,
    ) -> None:
        """Initialize the window and load data."""
        super().__init__(app_context, parent)
        self.setWindowTitle("Customers | العملاء")
        self._setup_ui()
        self.refresh_view()

    def _setup_ui(self) -> None:
        """Build the window UI."""
        # Header.
        header_layout = QHBoxLayout()
        title_label = QLabel("Customers | العملاء")
        title_label.setStyleSheet("font-size: 18px; font-weight: bold;")
        header_layout.addWidget(title_label)
        header_layout.addStretch()

        self.search_input = QLineEdit()
        self.search_input.setPlaceholderText("Search customers... | البحث في العملاء...")
        self.search_input.setMaximumWidth(300)
        self.search_input.textChanged.connect(self.refresh_view)
        header_layout.addWidget(self.search_input)

        add_btn = QPushButton("+ Add Customer | + إضافة عميل")
        add_btn.clicked.connect(self._add_customer)
        header_layout.addWidget(add_btn)

        self.main_layout.addLayout(header_layout)

        # Table.
        self.table = QTableWidget()
        self.table.setColumnCount(7)
        self.table.setHorizontalHeaderLabels([
            "Code | الرمز",
            "Name | الاسم",
            "Phone | الهاتف",
            "Email | البريد",
            "Credit Limit | الحد الائتماني",
            "Balance | الرصيد",
            "Status | الحالة",
        ])
        self.table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.table.doubleClicked.connect(self._edit_customer)
        self.main_layout.addWidget(self.table)

        # Action buttons.
        action_layout = QHBoxLayout()
        action_layout.addStretch()

        edit_btn = QPushButton("Edit | تعديل")
        edit_btn.clicked.connect(self._edit_customer)
        action_layout.addWidget(edit_btn)

        delete_btn = QPushButton("Delete | حذف")
        delete_btn.clicked.connect(self._delete_customer)
        action_layout.addWidget(delete_btn)

        view_btn = QPushButton("View | عرض")
        view_btn.clicked.connect(self._view_item)
        action_layout.addWidget(view_btn)

        self.main_layout.addLayout(action_layout)

    # ========================
    # Data loading
    # ========================

    def load_data(self, session: Session) -> None:
        """
        Load customers from the database into the table.

        Args:
            session: Database session provided by ``refresh_view``.
        """
        query = session.query(Customer)

        search_term = (
            self.search_input.text().strip() if hasattr(self, "search_input") else ""
        )
        if search_term:
            pattern = f"%{search_term}%"
            query = query.filter(
                (Customer.code.ilike(pattern))
                | (Customer.name.ilike(pattern))
                | (Customer.name_ar.ilike(pattern))
                | (Customer.phone.ilike(pattern))
                | (Customer.email.ilike(pattern))
            )

        customers = query.order_by(Customer.code).limit(500).all()

        if not hasattr(self, "table"):
            return

        self.table.setRowCount(len(customers))
        for row, customer in enumerate(customers):
            credit_limit = (
                f"{customer.credit_limit:,.2f}"
                if customer.credit_limit is not None
                else ""
            )
            balance = (
                f"{customer.credit_balance:,.2f}"
                if customer.credit_balance is not None
                else "0.00"
            )
            self.table.setItem(row, 0, QTableWidgetItem(customer.code or ""))
            self.table.setItem(row, 1, QTableWidgetItem(customer.name or ""))
            self.table.setItem(row, 2, QTableWidgetItem(customer.phone or ""))
            self.table.setItem(row, 3, QTableWidgetItem(customer.email or ""))
            self.table.setItem(row, 4, QTableWidgetItem(credit_limit))
            self.table.setItem(row, 5, QTableWidgetItem(balance))
            self.table.setItem(
                row,
                6,
                QTableWidgetItem(
                    "Active | نشط" if customer.is_active else "Inactive | غير نشط"
                ),
            )
            # Store the customer id on the first column for later lookups.
            self.table.item(row, 0).setData(Qt.ItemDataRole.UserRole, customer.id)

    def _selected_customer_id(self) -> Optional[Any]:
        """Return the id of the currently selected row, or None."""
        current_row = self.table.currentRow()
        if current_row < 0:
            self._show_warning(
                "Please select a customer first. | يرجى اختيار عميل أولاً."
            )
            return None
        return self.table.item(current_row, 0).data(Qt.ItemDataRole.UserRole)

    # ========================
    # CREATE
    # ========================

    def _add_customer(self) -> None:
        """Open the dialog to create a new customer."""
        dialog = CustomerDialog(parent=self)
        if dialog.exec() == QDialog.DialogCode.Accepted:
            self._save_customer(dialog.get_customer_data())

    def _save_customer(self, data: Dict[str, Any]) -> None:
        """Persist a new customer via the service layer."""
        service = get_customer_service()

        # Resolve the owning company from the active session/user.
        company_id = self._resolve_company_id()
        if company_id is None:
            self._show_error(
                "No active company found. | لا توجد شركة نشطة."
            )
            return
        data["company_id"] = company_id

        try:
            with session_scope() as session:
                instance, errors = service.create(session, data)
                if errors:
                    self._display_validation_errors(errors)
                    return
                self._show_info(
                    "Customer created successfully.\n\nتم إنشاء العميل بنجاح.",
                    "Success | نجاح",
                )
                self.refresh_view()
        except Exception as exc:  # noqa: BLE001 - surfaced to the user with an id
            self._handle_unexpected_error("create", exc)

    # ========================
    # UPDATE
    # ========================

    def _edit_customer(self) -> None:
        """Open the dialog to edit the selected customer."""
        customer_id = self._selected_customer_id()
        if customer_id is None:
            return

        db = SessionLocal()
        try:
            customer = db.query(Customer).filter(Customer.id == customer_id).first()
            if not customer:
                self._show_warning("Customer not found. | العميل غير موجود.")
                return
            dialog = CustomerDialog(customer=customer, parent=self)
            if dialog.exec() == QDialog.DialogCode.Accepted:
                self._update_customer(customer_id, dialog.get_customer_data())
        finally:
            db.close()

    def _update_customer(self, customer_id: Any, data: Dict[str, Any]) -> None:
        """Persist updates to an existing customer via the service layer."""
        service = get_customer_service()
        try:
            with session_scope() as session:
                instance, errors = service.update(session, customer_id, data)
                if errors:
                    self._display_validation_errors(errors)
                    return
                self._show_info(
                    "Customer updated successfully.\n\nتم تحديث العميل بنجاح.",
                    "Success | نجاح",
                )
                self.refresh_view()
        except Exception as exc:  # noqa: BLE001
            self._handle_unexpected_error("update", exc)

    # ========================
    # DELETE
    # ========================

    def _delete_customer(self) -> None:
        """Soft-delete the selected customer via the service layer."""
        current_row = self.table.currentRow()
        if current_row < 0:
            self._show_warning(
                "Please select a customer to delete. | يرجى اختيار عميل للحذف."
            )
            return

        name = self.table.item(current_row, 1).text()
        if not self._ask_confirmation(
            f"Are you sure you want to delete customer '{name}'?\n\n"
            f"هل أنت متأكد من حذف العميل '{name}'؟",
            "Confirm Delete | تأكيد الحذف",
        ):
            return

        customer_id = self.table.item(current_row, 0).data(Qt.ItemDataRole.UserRole)
        service = get_customer_service()
        try:
            with session_scope() as session:
                success, errors = service.delete(session, customer_id)
                if not success or errors:
                    self._display_validation_errors(errors)
                    return
                self._show_info(
                    "Customer deleted successfully.\n\nتم حذف العميل بنجاح.",
                    "Success | نجاح",
                )
                self.refresh_view()
        except Exception as exc:  # noqa: BLE001
            self._handle_unexpected_error("delete", exc)

    # ========================
    # VIEW
    # ========================

    def _view_item(self) -> None:
        """Show a read-only summary of the selected customer."""
        customer_id = self._selected_customer_id()
        if customer_id is None:
            return

        db = SessionLocal()
        try:
            customer = db.query(Customer).filter(Customer.id == customer_id).first()
            if not customer:
                self._show_warning("Customer not found. | العميل غير موجود.")
                return
            credit_limit = (
                f"{customer.credit_limit:,.2f}"
                if customer.credit_limit is not None
                else "-"
            )
            balance = (
                f"{customer.credit_balance:,.2f}"
                if customer.credit_balance is not None
                else "0.00"
            )
            details = (
                f"Code | الرمز: {customer.code}\n"
                f"Name | الاسم: {customer.name}\n"
                f"Name (AR) | الاسم (عربي): {customer.name_ar or '-'}\n"
                f"Phone | الهاتف: {customer.phone or '-'}\n"
                f"Email | البريد: {customer.email or '-'}\n"
                f"Tax ID | الرقم الضريبي: {customer.tax_id or '-'}\n"
                f"Address | العنوان: {customer.address or '-'}\n"
                f"Credit Limit | الحد الائتماني: {credit_limit}\n"
                f"Balance | الرصيد: {balance}\n"
                f"Status | الحالة: "
                f"{'Active | نشط' if customer.is_active else 'Inactive | غير نشط'}"
            )
            self._show_info(details, "Customer Details | تفاصيل العميل")
        finally:
            db.close()

    # ========================
    # Helpers
    # ========================

    def _resolve_company_id(self) -> Optional[Any]:
        """
        Resolve the company id for new records.

        Prefers the active user from the session manager (matching the
        products window pattern), falling back to the app context.
        """
        try:
            from core.session_manager import session_manager

            current_user = session_manager.get_active_user()
            if current_user and getattr(current_user, "company_id", None):
                return current_user.company_id
        except Exception:  # noqa: BLE001 - fall back to context below
            logger.debug("session_manager unavailable; falling back to app_context")

        current_company = self.app_context.get("current_company")
        if current_company is not None:
            return getattr(current_company, "id", None)

        current_user = self.app_context.get("current_user")
        if current_user is not None:
            return getattr(current_user, "company_id", None)
        return None

    def _display_validation_errors(self, errors: list) -> None:
        """Show bilingual validation errors to the user."""
        if not errors:
            return
        en_msgs = [f"- {e.get_message('en')} (field: {e.field})" for e in errors]
        ar_msgs = [f"- {e.get_message('ar')} (الحقل: {e.field})" for e in errors]
        message = (
            "Validation errors occurred:\n"
            + "\n".join(en_msgs)
            + "\n\nحدثت أخطاء في التحقق:\n"
            + "\n".join(ar_msgs)
        )
        self._show_error(message, title="Validation | التحقق")

    def _handle_unexpected_error(self, action: str, exc: Exception) -> None:
        """Log and surface an unexpected error with a trace id."""
        error_id = str(uuid.uuid4())[:8]
        logger.exception("Customer %s error %s: %s", action, error_id, exc)
        self._show_error(
            f"Failed to {action} customer | فشل {action} العميل\n"
            f"Error ID: {error_id}\nDetails: {exc}",
            title="Error | خطأ",
        )
